# Generated by Django 4.0.6 on 2022-07-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=70, verbose_name='Отделение')),
                ('second_name_doctor', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name_doctor', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name_doctor', models.CharField(max_length=50, verbose_name='Отчествво')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('experience', models.IntegerField(verbose_name='Опыт работы')),
                ('about_doctor', models.TextField(verbose_name='О докторе')),
            ],
        ),
    ]
