# Generated by Django 4.0.6 on 2022-07-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50, verbose_name='Назавание отделения')),
                ('department_info', models.TextField(verbose_name='Что лечат в этом отделении')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_name_patient', models.CharField(max_length=50, verbose_name='Фамилия пациента')),
                ('first_name_patient', models.CharField(max_length=50, verbose_name='Имя пациента')),
                ('last_name_patient', models.CharField(max_length=50, verbose_name='Отчествво пациента')),
                ('age_patient', models.IntegerField(verbose_name='Возраст пациента')),
                ('complaints', models.TextField(verbose_name='Жалобы пациента')),
                ('date_start', models.DateField(verbose_name='Начало лечения')),
                ('date_finish', models.DateField(verbose_name='Конец лечения')),
                ('second_name_doctor', models.CharField(max_length=50, verbose_name='Фамилия доктора')),
                ('first_name_doctor', models.CharField(max_length=50, verbose_name='Имя доктора')),
                ('last_name_doctor', models.CharField(max_length=50, verbose_name='Отчествво доктора')),
                ('diagnosis', models.CharField(max_length=50, verbose_name='Диагноз')),
            ],
            options={
                'verbose_name': 'Диагноз',
                'verbose_name_plural': 'Диагнозы',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=70, verbose_name='Отделение')),
                ('number', models.IntegerField(verbose_name='Номер палаты')),
                ('status', models.BooleanField(default=True, verbose_name='Свободна палата')),
            ],
            options={
                'verbose_name': 'Палата',
                'verbose_name_plural': 'Палаты',
            },
        ),
        migrations.AlterModelOptions(
            name='doctors',
            options={'verbose_name': 'Доктор', 'verbose_name_plural': 'Доктора'},
        ),
    ]
